/* eslint-disable max-len */

export const test = [
  { id: 1,
    a: 'Są przypadki kiedy pozwalam innym wziąć odpowiedzialność za rozwiązanie problemu.',
    b: 'Zamiast negocjować zagadnienia sporne, próbuję podkreślić zagadnienia w których się zgadzamy.',
  },
  { id: 2,
    a: 'Próbuję znaleźć rozwiązanie kompromisowe.',
    b: 'Próbuję rozważyć wszystkie wątpliwości obu stron.',
  },
  { id: 3,
    a: 'Zazwyczaj twardo dążę do realizacji wyznaczonych celów.',
    b: 'Mógłbym spróbować uspokoić odczucia innych i zachować nasze stosunki.',
  },
  { id: 4,
    a: 'Próbuję znaleźć rozwiązanie kompromisowe.',
    b: 'Czasami poświęcam własne życzenia dla życzeń innej osoby.',
  },
  { id: 5,
    a: 'Stale szukam pomocy innych przy wypracowaniu rozwiązania.',
    b: 'Próbuję robić to co jest konieczne aby uniknąć niepotrzebnych napięć.',
  },
  { id: 6,
    a: 'Próbuję unikać stwarzania sobie nieprzyjemności.',
    b: 'Próbuję wygrać swoją pozycję.' },
  { id: 7,
    a: 'Próbuję odłożyć problem do chwili kiedy mam trochę czasu na przemyślenie go.',
    b: 'Rezygnuję z pewnych punktów w zamian za inne.',
  },
  { id: 8,
    a: 'Zazwyczaj twardo dążę do realizacji swych celów.',
    b: 'Próbuję natychmiast wyjawić wszystkie zastrzeżenia i problemy.',
  },
  { id: 9,
    a: 'Uważam że różnice nie zawsze są warte martwienia się o nie.',
    b: 'Wkładam trochę wysiłku w osiągnięcie swojego celu.',
  },
  { id: 10,
    a: 'Twardo dążą do realizacji swych celów.',
    b: 'Próbuję znaleźć rozwiązanie kompromisowe.',
  },
  { id: 11,
    a: 'Próbuję natychmiast wyjawić wszystkie zastrzeżenia i problemy.',
    b: 'Mógłbym spróbować uspokoić odczucia innych i zachować nasze stosunki.',
  },
  { id: 12,
    a: 'Czasem unikam zajmowania stanowiska, które powodowałoby kontrowersje.',
    b: 'Pozwolę mu utrzymać kilka jego punktów jeśli on pozwoli mi utrzymać kilka moich.',
  },
  { id: 13,
    a: 'Proponuję rozwiązanie pośrednie.',
    b: 'Obstaję przy realizacji swoich punktów.',
  },
  { id: 14,
    a: 'Przedstawiam mu swoje poglądy i pytam o jego.',
    b: 'Próbuję wykazać mu logiczność i korzyści mojego stanowiska.',
  },
  { id: 15,
    a: 'Mógłbym spróbować uspokoić odczucia innych i zachować nasze stosunki.',
    b: 'Próbuję robić to co jest konieczne aby uniknąć napięć.',
  },
  { id: 16,
    a: 'Próbuję nie ranić uczuć innej osoby.',
    b: 'Próbuję przekonać inną osobę o zaletach mojego stanowiska.',
  },
  { id: 17,
    a: 'Zazwyczaj twardo dążę do realizacji swych celów.',
    b: 'Próbuję robić to, co jest konieczne aby uniknąć niepotrzebnych napięć.',
  },
  { id: 18,
    a: 'Jeżeli uszczęśliwi to drugą osobę, mogę pozwolić jej na zachowanie swych poglądów.',
    b: 'Pozwolę mu utrzymać kilka jego punktów jeśli on pozwoli mi utrzymać kilka moich.',
  },
  { id: 19,
    a: 'Próbuję natychmiast wyjawić wszystkie zastrzeżenia i problemy.',
    b: 'Próbuję odłożyć problem do chwili kiedy mam trochę czasu na przemyślenie go.',
  },
  { id: 20,
    a: 'Próbuję natychmiast zniwelować różnice naszych stanowisk.',
    b: 'Próbuję znaleźć uczciwą kombinację zysków i strat dla nas obu.',
  },
  { id: 21,
    a: 'W nadchodzących negocjacjach spróbuję zwracać uwagę na życzenia drugiej osoby.',
    b: 'Zawsze skłaniam się ku bezpośredniemu przedyskutowaniu problemu.',
  },
  { id: 22,
    a: 'Próbuję znaleźć stanowisko pośrednie między jego a moim.',
    b: 'Domagam się uznania swoich życzeń.',
  },
  { id: 23,
    a: 'Bardzo często staram się zaspokoić wszystkie nasze życzenia.',
    b: 'Są przypadki kiedy pozwalam innym wziąć odpowiedzialność za rozwiązanie problemu.',
  },
  { id: 24,
    a: 'Jeżeli stanowisko drugiego wydaje się być dla niego bardzo ważne, spróbowałbym wyjść naprzeciw jego życzeniom.',
    b: 'Próbuję zmusić go do rozwiązania kompromisowego.',
  },
  { id: 25,
    a: 'Próbuję wykazać logiczne korzyści mojego postępowania.',
    b: 'W nadchodzących negocjacjach spróbuję zwracać uwagę na życzenia drugiej strony.',
  },
  { id: 26,
    a: 'Proponuję rozwiązanie pośrednie.',
    b: 'Prawie zawsze staram się zaspokoić wszystkie nasze życzenia.',
  },
  { id: 27,
    a: 'Czasem unikam zajmowania stanowiska, które powodowałoby kontrowersje.',
    b: 'Jeżeli uszczęśliwi to drugą osobę, mogę pozwolić jej na zachowanie swych poglądów.',
  },
  { id: 28,
    a: 'Zazwyczaj twardo dążę do realizacji swych celów.',
    b: 'Zazwyczaj szukam pomocy innych przy wypracowywaniu rozwiązania.',
  },
  { id: 29,
    a: 'Proponuję rozwiązanie pośrednie.',
    b: 'Uważam, że różnice nie zawsze są warte martwienia się o nie.',
  },
  { id: 30,
    a: 'Próbuję nie ranić uczuć innej osoby',
    b: 'Zawsze dzielę się problemem z inną osobą, abyśmy mogli go razem rozwiązać.',
  },
];

export const test_key = [
  { id: 1, competition: null, cooperation: null, compromise: null, avoidance: 'A', quadrating: 'B' },
  { id: 2, competition: null, cooperation: 'B', compromise: 'A', avoidance: null, quadrating: null },
  { id: 3, competition: 'A', cooperation: null, compromise: null, avoidance: null, quadrating: 'B' },
  { id: 4, competition: null, cooperation: null, compromise: 'A', avoidance: null, quadrating: 'B' },
  { id: 5, competition: null, cooperation: 'A', compromise: null, avoidance: 'B', quadrating: null },
  { id: 6, competition: 'B', cooperation: null, compromise: null, avoidance: 'A', quadrating: null },
  { id: 7, competition: null, cooperation: null, compromise: 'B', avoidance: 'A', quadrating: null },
  { id: 8, competition: 'A', cooperation: 'B', compromise: null, avoidance: null, quadrating: null },
  { id: 9, competition: 'B', cooperation: null, compromise: null, avoidance: 'A', quadrating: null },
  { id: 10, competition: 'A', cooperation: null, compromise: 'B', avoidance: null, quadrating: null },
  { id: 11, competition: null, cooperation: 'A', compromise: null, avoidance: null, quadrating: 'B' },
  { id: 12, competition: null, cooperation: null, compromise: 'B', avoidance: 'A', quadrating: null },
  { id: 13, competition: 'B', cooperation: null, compromise: 'A', avoidance: null, quadrating: null },
  { id: 14, competition: 'B', cooperation: 'A', compromise: null, avoidance: null, quadrating: null },
  { id: 15, competition: null, cooperation: null, compromise: null, avoidance: 'B', quadrating: 'A' },
  { id: 16, competition: 'B', cooperation: null, compromise: null, avoidance: null, quadrating: 'A' },
  { id: 17, competition: 'A', cooperation: null, compromise: null, avoidance: 'B', quadrating: null },
  { id: 18, competition: null, cooperation: null, compromise: 'B', avoidance: null, quadrating: 'A' },
  { id: 19, competition: null, cooperation: 'A', compromise: null, avoidance: 'B', quadrating: null },
  { id: 20, competition: null, cooperation: 'A', compromise: 'B', avoidance: null, quadrating: null },
  { id: 21, competition: null, cooperation: 'B', compromise: null, avoidance: null, quadrating: 'A' },
  { id: 22, competition: 'B', cooperation: null, compromise: 'A', avoidance: null, quadrating: null },
  { id: 23, competition: null, cooperation: 'A', compromise: null, avoidance: 'B', quadrating: null },
  { id: 24, competition: null, cooperation: null, compromise: 'B', avoidance: null, quadrating: 'A' },
  { id: 25, competition: 'A', cooperation: null, compromise: null, avoidance: null, quadrating: 'B' },
  { id: 26, competition: null, cooperation: 'B', compromise: 'A', avoidance: null, quadrating: null },
  { id: 27, competition: null, cooperation: null, compromise: null, avoidance: 'A', quadrating: 'B' },
  { id: 28, competition: 'A', cooperation: 'B', compromise: null, avoidance: null, quadrating: null },
  { id: 29, competition: null, cooperation: null, compromise: 'A', avoidance: 'B', quadrating: null },
  { id: 30, competition: null, cooperation: 'B', compromise: null, avoidance: null, quadrating: 'A' },
];
